start:
  - parallel_threads:
      - guardrails
      - inference_pipeline
  - post_treatment

inference_pipeline:
  - pre_treatment
  - data_retrieval
  - augmented_generation

guardrails:
  - RAGGuardrails.guardrails_query_analysis

pre_treatment:  
  - parallel_threads:
      - RAGPreTreatment.bypassed_analyse_query_language
      - RAGPreTreatment.analyse_query_for_metadata
      - RAGPreTreatment.extract_explicit_metadata
  - RAGPreTreatment.get_merged_metadata

data_retrieval:
  - parallel_threads:
      - RAGHybridRetrieval.semantic_vector_retrieval
      - RAGHybridRetrieval.bm25_retrieval
  - RAGHybridRetrieval.hybrid_chunks_selection

augmented_generation:
  - RAGAugmentedGeneration.rag_augmented_answer_generation

post_treatment:
  - RAGPostTreatment.response_post_treatment
