start:
  - parallel_threads:
      - guardrails
      - inference_pipeline
  - post_treatment

guardrails:
  - RAGGuardrails.guardrails_query_analysis

inference_pipeline:
  - pre_treatment
  - data_retrieval
  - augmented_generation

pre_treatment:  
  - parallel_threads:
  # - RAGPreTreatment.query_translation
    - RAGPreTreatment.bypassed_query_translation

  # - RAGPreTreatment.bypassed_analyse_query_for_metadata
    - RAGPreTreatment.analyse_query_for_metadata    
    - RAGPreTreatment.extract_explicit_metadata
  - RAGPreTreatment.metadata_filters_validation_and_correction

data_retrieval:
# - parallel_threads:
#     - RAGHybridRetrieval.semantic_vector_retrieval
#     - RAGHybridRetrieval.bm25_retrieval
# - RAGHybridRetrieval.hybrid_chunks_selection
  - RAGHybridRetrieval.rag_hybrid_retrieval_langchain

augmented_generation:
  - RAGAugmentedGeneration.rag_augmented_answer_generation

post_treatment:
  - RAGPostTreatment.response_post_treatment
