/**
 * MAREE - level data.
 *
 * Each level is a compact top-down grid rather than a full stack of ASCII
 * layers: `floor` gives one digit per column (its rock floor height, 0-9;
 * a space means "no column here", the edge of the level's footprint) and
 * `basin` gives one letter per column (its basin id, or "." for dry land that
 * never floods). world.js expands this into the full voxel column model at
 * load time. `par` is the number of water level changes and gate toggles the
 * author needed to solve the level; the medal awarded compares the player's
 * own move count against it (see main.js).
 */

export const LEVELS = [
  {
    id: 'l01',
    name: 'Premiere maree',
    hint: 'Une caisse de bois suit toujours la surface : montez l\'eau pour qu\'elle devienne une marche.',
    w: 3,
    d: 3,
    h: 3,
    floor: ['202', '202', '202'],
    basin: ['.a.', '.a.', '.a.'],
    wood: [{ x: 1, z: 1 }],
    basins: { a: { level: 0 } },
    start: { x: 0, z: 1 },
    exit: { x: 2, z: 1 },
    par: 1,
  },
  {
    id: 'l02',
    name: 'Pierre qui coule',
    hint: 'Une pierre comble le trou, mais un niveau trop haut la noie : baissez l\'eau pour degager le passage.',
    w: 3,
    d: 3,
    h: 5,
    floor: ['202', '202', '202'],
    basin: ['.a.', '.a.', '.a.'],
    stone: [{ x: 1, z: 0 }, { x: 1, z: 1 }, { x: 1, z: 2 }],
    basins: { a: { level: 3 } },
    start: { x: 0, z: 1 },
    exit: { x: 2, z: 1 },
    par: 1,
  },
  {
    id: 'l03',
    name: 'La vanne',
    hint: 'Une vanne relie deux bassins : ouverte, ils partagent un seul niveau d\'eau.',
    w: 5,
    d: 1,
    h: 5,
    floor: ['40404'],
    basin: ['.a.b.'],
    wood: [{ x: 1, z: 0 }, { x: 3, z: 0 }],
    gates: [{ a: 'a', b: 'b', x: 2, z: 0 }],
    basins: { a: { level: 0 }, b: { level: 0 } },
    start: { x: 0, z: 0 },
    exit: { x: 4, z: 0 },
    par: 4,
  },
  {
    id: 'l04',
    name: 'Gel et degel',
    hint: 'Une eau stable deux secondes durcit en glace pour toujours. Chaque bassin se gere seul.',
    w: 6,
    d: 1,
    h: 5,
    floor: ['300011'],
    basin: ['.aaab.'],
    basins: { a: { level: 0, freeze: true }, b: { level: 3, freeze: false } },
    start: { x: 0, z: 0 },
    exit: { x: 5, z: 0 },
    par: 3,
  },
  {
    id: 'l05',
    name: 'Trois bassins',
    hint: 'Relier plusieurs bassins avant de monter l\'eau economise des gestes.',
    w: 7,
    d: 1,
    h: 5,
    floor: ['3030303'],
    basin: ['.a.b.c.'],
    wood: [{ x: 1, z: 0 }, { x: 3, z: 0 }, { x: 5, z: 0 }],
    gates: [
      { a: 'a', b: 'b', x: 2, z: 0 },
      { a: 'b', b: 'c', x: 4, z: 0 },
    ],
    basins: { a: { level: 0 }, b: { level: 0 }, c: { level: 0 } },
    start: { x: 0, z: 0 },
    exit: { x: 6, z: 0 },
    par: 4,
  },
  {
    id: 'l06',
    name: 'Le lac carre',
    hint: 'Le bassin est large : chaque caisse qui le traverse doit flotter, pas seulement celles du bord.',
    w: 5,
    d: 5,
    h: 5,
    floor: ['33333', '30003', '30003', '30003', '33333'],
    basin: ['.....', '.aaa.', '.aaa.', '.aaa.', '.....'],
    wood: [{ x: 1, z: 2 }, { x: 2, z: 2 }, { x: 3, z: 2 }],
    basins: { a: { level: 0 } },
    start: { x: 0, z: 2 },
    exit: { x: 4, z: 2 },
    par: 2,
  },
  {
    id: 'l07',
    name: 'Ne pas tout melanger',
    hint: 'Une vanne ouverte entre deux bassins ramene les deux au niveau le plus bas. Reflechissez avant d\'ouvrir.',
    w: 5,
    d: 1,
    h: 5,
    floor: ['30303'],
    basin: ['.a.b.'],
    wood: [{ x: 1, z: 0 }, { x: 3, z: 0 }],
    gates: [{ a: 'a', b: 'b', x: 2, z: 0 }],
    basins: { a: { level: 2 }, b: { level: 0 } },
    start: { x: 0, z: 0 },
    exit: { x: 4, z: 0 },
    par: 2,
  },
  {
    id: 'l08',
    name: 'Longue traversee',
    hint: 'Un large bassin a besoin de glace pour se traverser a pied sec.',
    w: 7,
    d: 1,
    h: 6,
    floor: ['3000004'],
    basin: ['.aaaab.'],
    wood: [{ x: 5, z: 0 }],
    basins: { a: { level: 0, freeze: true }, b: { level: 0, freeze: false } },
    start: { x: 0, z: 0 },
    exit: { x: 6, z: 0 },
    par: 5,
  },
  {
    id: 'l09',
    name: 'Bassins jumeaux',
    hint: 'Deux lacs, une vanne : un seul geste peut faire monter les deux ensemble.',
    w: 7,
    d: 5,
    h: 5,
    floor: ['3333333', '3003003', '3003003', '3003003', '3333333'],
    basin: ['.......', '.aa.bb.', '.aa.bb.', '.aa.bb.', '.......'],
    wood: [{ x: 1, z: 2 }, { x: 2, z: 2 }, { x: 4, z: 2 }, { x: 5, z: 2 }],
    gates: [{ a: 'a', b: 'b', x: 3, z: 2 }],
    basins: { a: { level: 0 }, b: { level: 0 } },
    start: { x: 0, z: 2 },
    exit: { x: 6, z: 2 },
    par: 3,
  },
  {
    id: 'l10',
    name: 'Le pont de glace',
    hint: 'La glace se forme d\'un cote, une caisse flotte de l\'autre : la vanne les eleve ensemble.',
    w: 7,
    d: 1,
    h: 5,
    floor: ['3000203'],
    basin: ['.aaa.b.'],
    wood: [{ x: 5, z: 0 }],
    gates: [{ a: 'a', b: 'b', x: 4, z: 0 }],
    basins: { a: { level: 0, freeze: true }, b: { level: 0, freeze: false } },
    start: { x: 0, z: 0 },
    exit: { x: 6, z: 0 },
    par: 3,
  },
  {
    id: 'l11',
    name: 'Piege de maree',
    hint: 'Une pierre bien placee n\'a besoin de rien. Ne noyez pas ce qui fonctionne deja.',
    w: 5,
    d: 1,
    h: 5,
    floor: ['20204'],
    basin: ['.a.b.'],
    stone: [{ x: 1, z: 0 }],
    wood: [{ x: 3, z: 0 }],
    gates: [{ a: 'a', b: 'b', x: 2, z: 0 }],
    basins: { a: { level: 0, freeze: false }, b: { level: 0, freeze: false } },
    start: { x: 0, z: 0 },
    exit: { x: 4, z: 0 },
    par: 3,
  },
  {
    id: 'l12',
    name: 'Grand bassin',
    hint: 'De la glace d\'un cote, du bois de l\'autre : une seule vanne peut mener les deux au but.',
    w: 7,
    d: 7,
    h: 5,
    floor: [
      '3333333',
      '3003003',
      '3003003',
      '3003003',
      '3003003',
      '3003003',
      '3333333',
    ],
    basin: [
      '.......',
      '.aa.bb.',
      '.aa.bb.',
      '.aa.bb.',
      '.aa.bb.',
      '.aa.bb.',
      '.......',
    ],
    wood: [{ x: 4, z: 3 }, { x: 5, z: 3 }],
    gates: [{ a: 'a', b: 'b', x: 3, z: 3 }],
    basins: { a: { level: 0, freeze: true }, b: { level: 0, freeze: false } },
    start: { x: 0, z: 3 },
    exit: { x: 6, z: 3 },
    par: 3,
  },
  {
    id: 'l13',
    name: 'La chaine',
    hint: 'Quatre bassins, trois vannes : reliez tout avant de monter, jamais apres.',
    w: 9,
    d: 1,
    h: 5,
    floor: ['404040404'],
    basin: ['.a.b.c.d.'],
    wood: [{ x: 1, z: 0 }, { x: 3, z: 0 }, { x: 5, z: 0 }, { x: 7, z: 0 }],
    gates: [
      { a: 'a', b: 'b', x: 2, z: 0 },
      { a: 'b', b: 'c', x: 4, z: 0 },
      { a: 'c', b: 'd', x: 6, z: 0 },
    ],
    basins: { a: { level: 0 }, b: { level: 0 }, c: { level: 0 }, d: { level: 0 } },
    start: { x: 0, z: 0 },
    exit: { x: 8, z: 0 },
    par: 6,
  },
  {
    id: 'l14',
    name: 'Confluence',
    hint: 'Glace, bois et pierre sur le meme parcours : la derniere vanne n\'est peut-etre pas necessaire.',
    w: 10,
    d: 7,
    h: 5,
    floor: [
      '4444444444',
      '4000400424',
      '4000400424',
      '4000400424',
      '4000400424',
      '4000400424',
      '4444444444',
    ],
    basin: [
      '..........',
      '.aaa.bb.c.',
      '.aaa.bb.c.',
      '.aaa.bb.c.',
      '.aaa.bb.c.',
      '.aaa.bb.c.',
      '..........',
    ],
    wood: [{ x: 5, z: 3 }, { x: 6, z: 3 }],
    stone: [
      { x: 8, z: 1 },
      { x: 8, z: 2 },
      { x: 8, z: 3 },
      { x: 8, z: 4 },
      { x: 8, z: 5 },
    ],
    gates: [
      { a: 'a', b: 'b', x: 4, z: 3 },
      { a: 'b', b: 'c', x: 7, z: 3 },
    ],
    basins: { a: { level: 0, freeze: true }, b: { level: 0, freeze: false }, c: { level: 0, freeze: false } },
    start: { x: 0, z: 3 },
    exit: { x: 9, z: 3 },
    par: 4,
  },
];
