"""Synthesis: render the Atlas Pack from module summaries and facts.

Two modes, one structure:
- LLM mode: writer agents produce prose docs from the verified summaries.
- Facts-only mode: deterministic templates render the same files from raw
  facts (tables instead of prose). The pack is always complete; the mode is
  stamped on every page so nobody mistakes one for the other.
"""

import json
import os

from . import prompts


def write_pack(out_dir, context, client=None, language="en"):
    """context: repo, stacks, meters, modules, summaries, edges, hotspots,
    deps, manifests, notes, git_by_module."""
    os.makedirs(os.path.join(out_dir, "03_modules"), exist_ok=True)
    mode = "llm" if client and client.available else "facts-only"
    stamp = (f"\n\n---\n*Generated by RepoAtlas engine ({mode} mode). "
             f"Every path cited is machine-verified; see verification_report.md.*\n")

    docs = {}
    preamble = prompts.WRITER_PREAMBLE.format(language=language)
    modules_json = json.dumps(context["summaries"], indent=1)

    if mode == "llm":
        shared = {
            "preamble": preamble, "repo": context["repo"],
            "stacks": ", ".join(context["stacks"]),
            "meters": json.dumps(context["meters"]),
            "modules_json": modules_json,
            "edges": json.dumps(context["edges"]),
            "deps": json.dumps(context["deps"][:30]),
            "hotspots": json.dumps(context["hotspots"]),
            "manifests": json.dumps(context["manifests"]),
            "risks_json": json.dumps([r for s in context["summaries"]
                                      for r in s.get("risks", [])], indent=1),
            "notes": json.dumps(context["notes"][:30]),
        }
        for name, template in prompts.DOC_PROMPTS.items():
            text = client.run(template.format(**shared), label=f"write_{name}")
            docs[name] = text or _fallback_doc(name, context)
        for summary in context["summaries"]:
            prompt = prompts.MODULE_DOC.format(
                preamble=preamble, module=summary["module"],
                summary_json=json.dumps(summary, indent=1),
                git=json.dumps(context["git_by_module"].get(summary["module"])))
            text = client.run(prompt, label=f"write_mod_{summary['module']}")
            docs[f"03_modules/{summary['module']}.md"] = \
                text or _module_doc_facts(summary, context)
    else:
        for name in prompts.DOC_PROMPTS:
            docs[name] = _fallback_doc(name, context)
        for summary in context["summaries"]:
            docs[f"03_modules/{summary['module']}.md"] = \
                _module_doc_facts(summary, context)

    docs["06_dependencies.md"] = _deps_doc(context)

    for name, text in docs.items():
        with open(os.path.join(out_dir, name), "w", encoding="utf-8") as fh:
            fh.write(text.rstrip() + stamp)
    return sorted(docs)


def _fallback_doc(name, context):
    build = {
        "01_overview.md": _overview_facts,
        "02_architecture.md": _architecture_facts,
        "07_onboarding.md": _onboarding_facts,
        "08_debt_register.md": _debt_facts,
    }[name]
    return build(context)


def _overview_facts(c):
    lines = [f"# {c['repo']}: overview", "",
             f"Stacks detected: {', '.join(c['stacks']) or 'unknown'}. "
             f"Meters: {c['meters']['code_kloc']}k lines of code across "
             f"{c['meters']['code_file_count']} files.", "",
             "## Modules", "", "| Module | Files | LOC |", "|---|---|---|"]
    for m in c["modules"]:
        lines.append(f"| {m['name']} | {len(m['files'])} | {m['loc']} |")
    routes = [r for s in c["summaries"] for r in s.get("entry_points", [])]
    if routes:
        lines += ["", "## Entry points / routes", "",
                  "| Where | Symbol | Role |", "|---|---|---|"]
        for r in routes[:40]:
            lines.append(f"| `{r['file']}` | {r['symbol']} | {r['role']} |")
    return "\n".join(lines)


def _architecture_facts(c):
    lines = ["# Architecture (module graph)", ""]
    if c["edges"]:
        lines += ["```mermaid", "graph LR"]
        for src, dst in c["edges"]:
            lines.append(f"  {_mid(src)}[{src}] --> {_mid(dst)}[{dst}]")
        lines += ["```", ""]
    else:
        lines.append("No inter-module import edges were detected.")
    lines += ["", "Edges are derived from import statements only; runtime "
              "coupling (HTTP, queues) is not shown."]
    return "\n".join(lines)


def _mid(name):
    return "m_" + "".join(ch if ch.isalnum() else "_" for ch in name)


def _onboarding_facts(c):
    lines = ["# Onboarding (facts-only)", "", "## Setup facts", ""]
    for m in c["manifests"]:
        lines.append(f"- `{m['file']}`: {m['note']}")
    lines += ["", "## Suggested reading order (by size and connectivity)", ""]
    for i, m in enumerate(c["modules"][:8], 1):
        lines.append(f"{i}. `{m['prefix']}` ({m['loc']} LOC)")
    lines += ["", "## Handle with care (hotspots)", ""]
    for h in c["hotspots"]:
        lines.append(f"- `{h['path']}` - {h['commits']} commits, "
                     f"{h['lines']} lines, bus factor {h['bus_factor']}")
    return "\n".join(lines)


def _debt_facts(c):
    lines = ["# Debt register (facts-only)", "",
             "| Priority | Signal | Evidence |", "|---|---|---|"]
    for h in c["hotspots"][:10]:
        prio = "P1" if h["bus_factor"] <= 1 else "P2"
        lines.append(f"| {prio} | high-churn file with bus factor "
                     f"{h['bus_factor']} | `{h['path']}` |")
    for note in c["notes"][:15]:
        lines.append(f"| P3 | scanner note: {note['note']} | `{note['file']}` |")
    return "\n".join(lines)


def _module_doc_facts(summary, c):
    lines = [f"# Module: {summary['module']}", "", summary.get("purpose", ""), ""]
    api = summary.get("public_api", [])
    if api:
        lines += ["## Symbols", "", "| Symbol | Kind | File |", "|---|---|---|"]
        for a in api:
            lines.append(f"| {a['symbol']} | {a['kind']} | `{a['file']}` |")
    git = c["git_by_module"].get(summary["module"])
    if git:
        lines += ["", f"Git: {git['commits']} commits, bus factor "
                  f"{git['bus_factor']}, last touched {git['last']}."]
    questions = summary.get("open_questions", [])
    if questions:
        lines += ["", "## Open questions", ""] + [f"- {q}" for q in questions]
    return "\n".join(lines)


def _deps_doc(c):
    lines = ["# Dependencies", "", "| Ecosystem | Package | Version | Declared in |",
             "|---|---|---|---|"]
    for d in sorted(c["deps"], key=lambda d: (d["ecosystem"], d["name"])):
        lines.append(f"| {d['ecosystem']} | {d['name']} | {d['version']} "
                     f"| `{d['file']}` |")
    return "\n".join(lines)
