crew:
  process: sequential
  verbose: 2
  memory: true
  agents:
    - role: Researcher
      goal: Investigate AI trends
      verbose: true
      tools: [search_tool]
      backstory: "A seasoned AI researcher dedicated to uncovering the latest trends in machine learning from search on the internet using tools."
      allow_delegation: false
    - role: Writer
      goal: Write articles on AI
      verbose: true
      tools: [search_tool]
      backstory: "An expert tech writer known for translating complex technical topics into engaging stories."
      allow_delegation: false
  tasks:
    - description: Identify key AI advancements
      agent: Researcher
      expected_output: Summary of advancements
    - description: Write an article on recent AI trends
      agent: Writer
      expected_output: Complete article
