extends WarTest
## The weapon table is pure data that the whole combat loop reads. A hole in it
## (a missing name, a zero fire rate, a sound key nobody generates) turns into a
## crash or a silent weapon the first time the player picks one up.


func suite_name() -> String:
	return "weapon_defs"


func test_every_weapon_is_complete() -> void:
	for id in WeaponDefs.all_ids():
		check(WeaponDefs.display_name(id) != "", "arme %d sans nom affichable" % id)
		check(WeaponDefs.damage(id) > 0.0, "arme %d sans degats" % id)
		check(WeaponDefs.magazine(id) > 0, "arme %d sans capacite de chargeur" % id)
		check(WeaponDefs.rpm(id) > 0.0, "arme %d sans cadence" % id)
		check(WeaponDefs.reload_time(id) > 0.0, "arme %d sans temps de rechargement" % id)
		check(WeaponDefs.fire_sample(id) != "", "arme %d sans echantillon de tir" % id)
		check(WeaponDefs.headshot_multiplier(id) >= 1.0,
				"arme %d : un tir a la tete doit faire au moins autant qu'au corps" % id)
	done()


func test_ids_are_contiguous_and_counted() -> void:
	var ids := WeaponDefs.all_ids()
	eq(ids.size(), WeaponDefs.COUNT, "all_ids() ne couvre pas COUNT armes")
	for id in ids:
		between(float(id), 0.0, float(WeaponDefs.COUNT - 1), "identifiant d'arme hors bornes")
	done()


func test_sound_keys_exist_in_the_sample_bank() -> void:
	# Every key the weapons ask for has to be generated by SfxLib, or the shot is
	# silent and nothing in the engine complains.
	for id in WeaponDefs.all_ids():
		var fire_key := WeaponDefs.fire_sample(id)
		check(SfxLib.NAMES.has(fire_key),
				"arme %d : echantillon de tir inconnu (%s)" % [id, fire_key])
		var reload_key := WeaponDefs.reload_sample(id)
		check(SfxLib.NAMES.has(reload_key),
				"arme %d : echantillon de rechargement inconnu (%s)" % [id, reload_key])
	done()


func test_falloff_is_monotonic_and_bounded() -> void:
	for id in WeaponDefs.all_ids():
		var previous := WeaponDefs.falloff(id, 0.0)
		between(previous, 0.0, 1.0, "arme %d : falloff a bout portant hors [0,1]" % id)
		for step in 20:
			var distance := float(step) * 25.0
			var value := WeaponDefs.falloff(id, distance)
			between(value, 0.0, 1.0, "arme %d : falloff hors [0,1] a %f m" % [id, distance])
			check(value <= previous + 0.001,
					"arme %d : le falloff remonte a %f m" % [id, distance])
			previous = value
		check(previous >= 0.3,
				"arme %d : le falloff lointain tombe trop bas (%f)" % [id, previous])
	done()


func test_aim_is_always_tighter_than_hip() -> void:
	for id in WeaponDefs.all_ids():
		if WeaponDefs.slot_of(id) == WeaponDefs.SLOT_THROWN:
			continue
		check(WeaponDefs.spread_aim(id) <= WeaponDefs.spread_hip(id),
				"arme %d : viser disperse plus que tirer a la hanche" % id)
		check(WeaponDefs.aim_fov_scale(id) <= 1.0,
				"arme %d : viser doit reduire le champ de vision, pas l'elargir" % id)
	done()


func test_bolt_action_rifles_hit_harder_than_submachine_guns() -> void:
	# This is the balance backbone: a rifle rewards precision, a submachine gun
	# rewards volume. If it inverts, the whole combat design is upside down.
	check(WeaponDefs.damage(WeaponDefs.SPRINGFIELD) > WeaponDefs.damage(WeaponDefs.THOMPSON),
			"la Springfield doit frapper plus fort que la Thompson")
	check(WeaponDefs.damage(WeaponDefs.KAR98K) > WeaponDefs.damage(WeaponDefs.MP40),
			"le Kar98k doit frapper plus fort que la MP40")
	check(WeaponDefs.rpm(WeaponDefs.THOMPSON) > WeaponDefs.rpm(WeaponDefs.SPRINGFIELD),
			"la Thompson doit tirer plus vite que la Springfield")
	check(WeaponDefs.is_automatic(WeaponDefs.THOMPSON), "la Thompson est automatique")
	check(not WeaponDefs.is_automatic(WeaponDefs.SPRINGFIELD),
			"la Springfield est a verrou, pas automatique")
	done()


func test_ammo_types_are_shared_the_way_history_says() -> void:
	eq(WeaponDefs.ammo_type(WeaponDefs.M1_GARAND),
			WeaponDefs.ammo_type(WeaponDefs.SPRINGFIELD),
			"Garand et Springfield partagent le .30-06")
	eq(WeaponDefs.ammo_type(WeaponDefs.THOMPSON), WeaponDefs.ammo_type(WeaponDefs.M1911),
			"Thompson et M1911 partagent le .45 ACP")
	eq(WeaponDefs.ammo_type(WeaponDefs.KAR98K), WeaponDefs.ammo_type(WeaponDefs.MG42),
			"Kar98k et MG42 partagent le 7.92 Mauser")
	ne(WeaponDefs.ammo_type(WeaponDefs.MP40), WeaponDefs.ammo_type(WeaponDefs.M1911),
			"le 9 mm de la MP40 n'est pas du .45 ACP")
	done()


func test_axis_weapons_are_flagged() -> void:
	check(WeaponDefs.is_axis_weapon(WeaponDefs.MP40), "la MP40 est une arme de l'Axe")
	check(WeaponDefs.is_axis_weapon(WeaponDefs.KAR98K), "le Kar98k est une arme de l'Axe")
	check(WeaponDefs.is_axis_weapon(WeaponDefs.MG42), "la MG42 est une arme de l'Axe")
	check(not WeaponDefs.is_axis_weapon(WeaponDefs.M1_GARAND), "le Garand est allie")
	check(not WeaponDefs.is_axis_weapon(WeaponDefs.THOMPSON), "la Thompson est alliee")
	done()


func test_slots_are_valid() -> void:
	eq(WeaponDefs.slot_of(WeaponDefs.M1911), WeaponDefs.SLOT_SECONDARY,
			"le M1911 est une arme de poing")
	eq(WeaponDefs.slot_of(WeaponDefs.GRENADE), WeaponDefs.SLOT_THROWN,
			"la grenade se lance")
	eq(WeaponDefs.slot_of(WeaponDefs.M1_GARAND), WeaponDefs.SLOT_PRIMARY,
			"le Garand est une arme principale")
	done()
