start:
  - parallel_threads:
      - guardrails_steps
      - inference_pipeline_steps

inference_pipeline_steps:
  - pre_treatment_steps
  - data_retrieval_steps
  - augmented_generation_steps
  - post_treatment_steps

guardrails_steps:
  - RAGGuardrails.guardrails_query_analysis

pre_treatment_steps:  
  - parallel_threads:
      - RAGPreTreatment.analyse_query_language
      - RAGPreTreatment.extract_explicit_metadata
      - RAGPreTreatment.analyse_query_for_metadata
  - RAGPreTreatment.output_mapper

data_retrieval_steps:
  - parallel_threads:
      - RAGHybridRetrieval.rag_retrieval
      - RAGHybridRetrieval.bm25_retrieval
  - RAGHybridRetrieval.hybrid_chunks_selection

augmented_generation_steps:
  - RAGAugmentedGeneration.rag_augmented_answer_generation

post_treatment_steps:
  - RAGPostTreatment.response_post_treatment
