"""Unit tests for `ProjectRunService` with the agents + LLM mocked.

Strategy: instead of mocking `common_tools.llm.Llm.ainvoke` (which the
service only touches indirectly through `DevAgent`, `QaAgent` and
`OrchestratorAgent`), we inject **fake agent factories** into the
service. Each fake agent implements the same async surface as its real
counterpart but returns hard-coded payloads.

This gives us:

- deterministic DevAgent output (a single file per task in a tmp dir),
- deterministic QaAgent verdicts (approved / rejected on demand),
- deterministic OrchestratorAgent picks (all executable tasks in order),

without ever hitting the LLM provider or importing common-tools.

We also override `session_factory` so the background task, which
normally opens fresh `AsyncSessionLocal` sessions, uses the in-memory
SQLite factory spun up by the test.
"""

from __future__ import annotations

import asyncio
from collections.abc import AsyncGenerator
from pathlib import Path
from uuid import UUID, uuid4

import pytest
import pytest_asyncio
from sqlalchemy.ext.asyncio import (
    AsyncSession,
    async_sessionmaker,
    create_async_engine,
)
from sqlalchemy.pool import StaticPool

from app.agents.dev_agent import DevAgentResult, DevFileOutput
from app.agents.orchestrator_agent import OrchestratorDecision
from app.agents.qa_agent import QaAgentResult, QaVerdict
from app.application.project_run_service import ProjectRunService
from app.infrastructure.entities import Base
from app.infrastructure.item_dependency_repository import (
    ItemDependencyRepository,
)
from app.infrastructure.item_repository import ItemRepository
from app.infrastructure.project_repository import ProjectRepository
from app.infrastructure.project_run_repository import ProjectRunRepository
from app.models.item import Item, ItemStatus, ItemType
from app.models.item_dependency import ItemDependency
from app.models.project import Project
from app.models.project_run import ProjectRunStatus


# ---------------------------------------------------------------------------
# Fake agents
# ---------------------------------------------------------------------------


class FakeDevAgent:
    """DevAgent replacement that writes a single file to a tmp dir."""

    def __init__(self, workspace_root: Path) -> None:
        self.workspace_root = workspace_root
        self.calls: list[UUID] = []

    async def aproduce_deliverable(
        self,
        task: Item,
        qa_feedback: str | None = None,
    ) -> DevAgentResult:
        assert task.id is not None
        self.calls.append(task.id)
        task_dir = self.workspace_root / str(task.project_id) / str(task.id)
        task_dir.mkdir(parents=True, exist_ok=True)
        file_path = task_dir / "main.py"
        file_path.write_text(
            f"# Generated by FakeDevAgent for {task.title}\nprint('hello')\n",
            encoding="utf-8",
        )
        return DevAgentResult(
            summary=f"Fake code for {task.title}",
            files=[
                DevFileOutput(
                    absolute_path=file_path,
                    relative_path="main.py",
                    language="python",
                ),
            ],
            raw_response={"summary": "fake"},
        )


class FakeQaAgentApprove:
    """QaAgent replacement that always approves."""

    async def areview_deliverable(
        self,
        task: Item,
        dev_result: DevAgentResult,
    ) -> QaAgentResult:
        return QaAgentResult(
            verdict=QaVerdict.APPROVED,
            feedback=f"OK for {task.title}",
            raw_response={"verdict": "approved"},
        )


class FakeQaAgentRejectThenApprove:
    """QaAgent that rejects the first call and approves the rest.

    Lets us exercise the dev/QA loop on a single task.
    """

    def __init__(self) -> None:
        self.calls = 0

    async def areview_deliverable(
        self,
        task: Item,
        dev_result: DevAgentResult,
    ) -> QaAgentResult:
        self.calls += 1
        if self.calls == 1:
            return QaAgentResult(
                verdict=QaVerdict.REJECTED,
                feedback="Missing tests.",
                raw_response={"verdict": "rejected"},
            )
        return QaAgentResult(
            verdict=QaVerdict.APPROVED,
            feedback="Fixed.",
            raw_response={"verdict": "approved"},
        )


class FakeQaAgentAlwaysReject:
    async def areview_deliverable(
        self,
        task: Item,
        dev_result: DevAgentResult,
    ) -> QaAgentResult:
        return QaAgentResult(
            verdict=QaVerdict.REJECTED,
            feedback="Still bad.",
            raw_response={"verdict": "rejected"},
        )


class FakeOrchestratorAgent:
    """OrchestratorAgent replacement: picks all executable tasks in order."""

    async def apick_next_batch(
        self,
        executable_tasks: list[Item],
        max_parallel: int,
    ) -> OrchestratorDecision:
        picks = [
            t.id
            for t in executable_tasks[:max_parallel]
            if t.id is not None
        ]
        return OrchestratorDecision(
            selected_task_ids=picks,
            rationale="Test fake: take everything.",
        )


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest_asyncio.fixture
async def run_env(
    tmp_path: Path,
) -> AsyncGenerator[tuple[async_sessionmaker[AsyncSession], Path], None]:
    """Provide a private in-memory DB + a sandbox workspace for DevAgents."""
    # StaticPool is required so the multiple short-lived sessions the
    # service opens (via `AsyncSessionLocal`) all hit the **same**
    # in-memory SQLite database. Without it, each new connection gets
    # its own empty `:memory:` and writes from iteration N are invisible
    # to iteration N+1.
    engine = create_async_engine(
        "sqlite+aiosqlite:///:memory:",
        future=True,
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
    )
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    session_factory = async_sessionmaker(
        bind=engine,
        expire_on_commit=False,
        autoflush=False,
        autocommit=False,
        class_=AsyncSession,
    )

    workspace = tmp_path / "generated"
    workspace.mkdir()

    try:
        yield session_factory, workspace
    finally:
        await engine.dispose()


async def _aseed_tasks(
    session_factory: async_sessionmaker[AsyncSession],
    *,
    count: int,
    deps: list[tuple[int, int]] | None = None,
) -> tuple[UUID, list[UUID]]:
    """Seed ``count`` TODO tasks with optional deps by task index.

    Deps is a list of `(downstream_idx, upstream_idx)` tuples meaning
    ``downstream depends on upstream``.
    """
    deps = deps or []
    async with session_factory() as session:
        project_repo = ProjectRepository(session)
        project = await project_repo.acreate_project(Project(name="RunSvcProj"))
        assert project.id is not None

        item_repo = ItemRepository(session)
        task_ids: list[UUID] = []
        for i in range(count):
            task = await item_repo.acreate_item(
                Item(
                    project_id=project.id,
                    type=ItemType.TASK,
                    title=f"Task {i}",
                    description=f"Does thing #{i}",
                    status=ItemStatus.TODO,
                ),
            )
            assert task.id is not None
            task_ids.append(task.id)

        dep_repo = ItemDependencyRepository(session)
        for downstream_idx, upstream_idx in deps:
            await dep_repo.acreate_dependency(
                ItemDependency(
                    item_id=task_ids[downstream_idx],
                    depends_on_item_id=task_ids[upstream_idx],
                ),
            )

        await session.commit()
        return project.id, task_ids


async def _await_run_status(
    session_factory: async_sessionmaker[AsyncSession],
    run_id: UUID,
    target_status: ProjectRunStatus,
    *,
    timeout_seconds: float = 5.0,
) -> None:
    """Poll the run status until it matches ``target_status`` or timeout."""
    deadline = asyncio.get_event_loop().time() + timeout_seconds
    while asyncio.get_event_loop().time() < deadline:
        async with session_factory() as session:
            repo = ProjectRunRepository(session)
            run = await repo.aget_run_by_id(run_id)
        if run is not None and run.status == target_status:
            return
        await asyncio.sleep(0.02)
    pytest.fail(
        f"Run {run_id} did not reach status {target_status} within "
        f"{timeout_seconds}s",
    )


def _build_service(
    session_factory: async_sessionmaker[AsyncSession],
    workspace: Path,
    *,
    qa_factory=lambda: FakeQaAgentApprove(),
) -> ProjectRunService:
    fake_dev = FakeDevAgent(workspace_root=workspace)
    return ProjectRunService(
        dev_agent_factory=lambda: fake_dev,  # type: ignore[arg-type,return-value]
        qa_agent_factory=qa_factory,  # type: ignore[arg-type]
        orchestrator_factory=lambda: FakeOrchestratorAgent(),  # type: ignore[arg-type,return-value]
        session_factory=session_factory,
        max_parallel=2,
        max_iterations=2,
    )


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_run_walks_linear_chain_to_success(run_env) -> None:
    """3 tasks, each depending on the previous → all end in ``done``."""
    session_factory, workspace = run_env
    project_id, task_ids = await _aseed_tasks(
        session_factory,
        count=3,
        deps=[(1, 0), (2, 1)],
    )

    service = _build_service(session_factory, workspace)

    async with session_factory() as session:
        run = await service.astart_project_run(
            session=session,
            project_id=project_id,
        )
        assert run.id is not None
        assert run.total_tasks == 3

    await _await_run_status(
        session_factory,
        run.id,
        ProjectRunStatus.SUCCEEDED,
    )

    async with session_factory() as session:
        item_repo = ItemRepository(session)
        items = await item_repo.aget_items_by_project(project_id)
    for task_id in task_ids:
        match = next(it for it in items if it.id == task_id)
        assert match.status == ItemStatus.DONE
        assert match.deliverable_paths == ["main.py"]


@pytest.mark.asyncio
async def test_run_refuses_second_concurrent_run(run_env) -> None:
    """Starting a second run while one is active raises `ProjectRunConflict`."""
    session_factory, workspace = run_env
    project_id, _ = await _aseed_tasks(session_factory, count=1)

    service = _build_service(session_factory, workspace)

    async with session_factory() as session:
        await service.astart_project_run(session=session, project_id=project_id)

    from app.application.project_run_service import ProjectRunConflict

    async with session_factory() as session:
        with pytest.raises(ProjectRunConflict):
            await service.astart_project_run(
                session=session,
                project_id=project_id,
            )


@pytest.mark.asyncio
async def test_run_retries_on_qa_reject_then_succeeds(run_env) -> None:
    """QA rejects once, dev retries, second QA approves → task done."""
    session_factory, workspace = run_env
    project_id, task_ids = await _aseed_tasks(session_factory, count=1)

    qa_fake = FakeQaAgentRejectThenApprove()
    service = _build_service(
        session_factory,
        workspace,
        qa_factory=lambda: qa_fake,
    )

    async with session_factory() as session:
        run = await service.astart_project_run(
            session=session,
            project_id=project_id,
        )
        assert run.id is not None

    await _await_run_status(
        session_factory,
        run.id,
        ProjectRunStatus.SUCCEEDED,
    )

    async with session_factory() as session:
        item_repo = ItemRepository(session)
        items = await item_repo.aget_items_by_project(project_id)
    task = next(it for it in items if it.id == task_ids[0])
    assert task.status == ItemStatus.DONE
    assert qa_fake.calls == 2
    assert task.deliverable_notes is not None
    assert "rejet" in task.deliverable_notes


@pytest.mark.asyncio
async def test_run_blocks_task_after_double_rejection(run_env) -> None:
    """QA rejects twice → task ends in ``blocked`` with a reason."""
    session_factory, workspace = run_env
    project_id, task_ids = await _aseed_tasks(session_factory, count=1)

    service = _build_service(
        session_factory,
        workspace,
        qa_factory=lambda: FakeQaAgentAlwaysReject(),
    )

    async with session_factory() as session:
        run = await service.astart_project_run(
            session=session,
            project_id=project_id,
        )
        assert run.id is not None

    await _await_run_status(
        session_factory,
        run.id,
        ProjectRunStatus.SUCCEEDED,
    )

    async with session_factory() as session:
        item_repo = ItemRepository(session)
        items = await item_repo.aget_items_by_project(project_id)
        run_repo = ProjectRunRepository(session)
        final_run = await run_repo.aget_run_by_id(run.id)

    task = next(it for it in items if it.id == task_ids[0])
    assert task.status == ItemStatus.BLOCKED
    assert task.blocked_reason is not None
    assert final_run is not None
    assert final_run.blocked_tasks == 1


@pytest.mark.asyncio
async def test_recover_orphan_runs_marks_them_failed(run_env) -> None:
    """`arecover_orphan_runs` flips running/pending rows to failed."""
    session_factory, workspace = run_env
    project_id, _ = await _aseed_tasks(session_factory, count=1)

    # Insert a bogus "running" run directly via the repository so it
    # looks exactly like the state a previous crashed process would
    # have left behind.
    from datetime import datetime, timezone
    from app.models.project_run import ProjectRun

    async with session_factory() as session:
        repo = ProjectRunRepository(session)
        orphan = await repo.acreate_run(
            ProjectRun(
                project_id=project_id,
                status=ProjectRunStatus.RUNNING,
                started_at=datetime.now(timezone.utc),
                total_tasks=1,
            ),
        )
        await session.commit()

    service = _build_service(session_factory, workspace)
    recovered = await service.arecover_orphan_runs()
    assert recovered == 1

    async with session_factory() as session:
        repo = ProjectRunRepository(session)
        run = await repo.aget_run_by_id(orphan.id)  # type: ignore[arg-type]
    assert run is not None
    assert run.status == ProjectRunStatus.FAILED
    assert run.error == "server_restart"


@pytest.mark.asyncio
async def test_compute_executable_tasks_filters_on_dep_status() -> None:
    """Pure-function test on the scheduler's core predicate."""
    project_id = uuid4()
    t0 = Item(
        id=uuid4(),
        project_id=project_id,
        type=ItemType.TASK,
        title="t0",
        status=ItemStatus.DONE,
    )
    t1 = Item(
        id=uuid4(),
        project_id=project_id,
        type=ItemType.TASK,
        title="t1",
        status=ItemStatus.TODO,
    )
    t2 = Item(
        id=uuid4(),
        project_id=project_id,
        type=ItemType.TASK,
        title="t2",
        status=ItemStatus.TODO,
    )
    deps = [
        (t1.id, t0.id),  # t1 depends on t0 (done)
        (t2.id, t1.id),  # t2 depends on t1 (todo) → t2 not executable yet
    ]
    executable = ProjectRunService._compute_executable_tasks(
        tasks=[t0, t1, t2],
        dependencies=deps,  # type: ignore[arg-type]
    )
    assert [it.id for it in executable] == [t1.id]
