## Imported rigged characters. This is the ONE place in CALL OF WAR that puts a
## binary mesh on screen; every other shape in the game is still generated by
## `Meshes`. The two glTF models under `assets/models` carry their own skeleton
## and animation set (see `assets/models/CREDITS.md` for sources and licences).
##
## The rule from `Tex` applies unchanged: an installed model overrides the
## procedural body, and deleting `assets/models` drops the game straight back to
## the box soldiers. `available()` is the single guard, and it caches its misses
## so an asset-less checkout costs one filesystem probe per species.
##
## Conventions this file has to reconcile:
##
## - Both models are authored facing **+Z**, while the whole project assumes a
##   soldier faces **-Z** (see the header of `Meshes`). The `Rig` node therefore
##   carries a 180 degree yaw, and everything below it is mirrored by that turn.
## - Both models are exported in centimetres and wrapped in an armature node
##   scaled by ~100. Anything parented to a bone inherits that factor, so the
##   weapon has to be counter-scaled or it shows up the size of a barn.
## - Heights below were measured from the posed skeleton, not from the mesh
##   bounding box: a skinned mesh stores its bounds in bind space, and the
##   zombie's are inflated by more than four metres. `tests/test_character_models.gd`
##   pins the resulting on-screen height so a re-import cannot silently drift.
class_name CharacterModels
extends RefCounted

const MODEL_DIR := "res://assets/models"

const SPECIES_SOLDIER := 0
const SPECIES_ZOMBIE := 1

## Every species is scaled to this, matching the 1.80 m of the box soldier so
## the capsule (1.75 m) and the headshot line (1.45 m) stay meaningful.
const TARGET_HEIGHT := 1.80

## Share of Axis spawns that wear the zombie model instead of the soldier one.
## Set it to 0.0 to put the whole Wehrmacht back in uniform.
const ZOMBIE_SHARE := 0.30

# Mirrors of War, duplicated for the same reason `Meshes` duplicates them: this
# file must compile under `--script`, where autoloads do not exist.
const _F_ALLIED := 0
const _F_AXIS := 1
const _F_NEUTRAL := 2

## Per species: the file, the measured height of the rest pose in the model's
## own units, the bone the weapon hangs off, the material names that get
## repainted in the faction colour, and the clip table.
##
## `height` is the figure that turns into the scale factor. It came from putting
## the model next to a 1.80 m post and reading the render, cross-checked against
## the skeleton bone extent; the mesh AABB disagrees and is wrong.
const _SPECIES := {
	SPECIES_SOLDIER: {
		"file": "soldier.glb",
		"height": 1.854,
		"hand_bone": "Wrist.R",
		"tint": ["Swat"],
		"prefix": "CharacterArmature|",
		"clips": {
			"idle": "Idle_Gun",
			"idle_aim": "Idle_Gun_Pointing",
			"walk": "Walk",
			"run": "Run",
			"run_aim": "Run_Shoot",
			"fire": "Gun_Shoot",
			"hit": "HitRecieve",
			"death": "Death",
		},
		# Clip lengths are authored for these ground speeds; playback is scaled
		# by the real speed so the feet stop skating.
		"walk_speed": 1.45,
		"run_speed": 4.60,
	},
	SPECIES_ZOMBIE: {
		"file": "zombie.glb",
		"height": 6.933,
		"hand_bone": "RightHand",
		"tint": [],
		"prefix": "Zombie|",
		"clips": {
			"idle": "ZombieIdle",
			"idle_aim": "ZombieIdle",
			"walk": "ZombieWalk",
			"run": "ZombieRun",
			"run_aim": "ZombieRun",
			"fire": "ZombieBite",
			# This rig ships neither a hit nor a death clip. Both keys are left
			# out on purpose: `CharacterAnim` reports the gap and `Soldier`
			# falls back to the procedural tip-over for the death.
		},
		"walk_speed": 1.10,
		"run_speed": 3.20,
	},
}

## Clips that must repeat. glTF import brings every animation in as one-shot.
const _LOOPING := ["idle", "idle_aim", "walk", "run", "run_aim"]

static var _scene_cache: Dictionary = {}
static var _tint_cache: Dictionary = {}


## True when this species has a model installed. Cached, misses included.
static func available(species: int) -> bool:
	return _scene(species) != null


## Which creature a spawn wears.
##
## Cosmetic only, and deliberately so: a zombie is an ordinary soldier with the
## same brain, the same rifle and the same cover logic. Nothing downstream
## branches on the answer, which is why it is decided once at spawn.
##
## It lives here rather than in the spawners because there are two of them,
## `Director._make_soldier` for lone sentries and `Squad._spawn_member` for
## everyone else, and a rule copied into both is a rule that drifts.
static func pick_species(faction: int, rng: RandomNumberGenerator) -> int:
	if faction != _F_AXIS or ZOMBIE_SHARE <= 0.0:
		return SPECIES_SOLDIER
	if not available(SPECIES_ZOMBIE):
		return SPECIES_SOLDIER
	var roll: float = rng.randf() if rng != null else randf()
	return SPECIES_ZOMBIE if roll < ZOMBIE_SHARE else SPECIES_SOLDIER


## The species' imported scene, or null when the file is absent or unreadable.
static func _scene(species: int) -> PackedScene:
	if _scene_cache.has(species):
		return _scene_cache[species] as PackedScene
	var found: PackedScene = null
	if _SPECIES.has(species):
		var path: String = "%s/%s" % [MODEL_DIR, _SPECIES[species]["file"]]
		if ResourceLoader.exists(path):
			found = load(path) as PackedScene
			if found != null:
				_prepare_loops(found, species)
	_scene_cache[species] = found
	return found


## Flips the looping clips to LOOP_LINEAR, once per species. The Animation
## resources are shared by every instance of the scene, so doing this at load
## time fixes all of them and repeating it is harmless.
static func _prepare_loops(scene: PackedScene, species: int) -> void:
	var probe := scene.instantiate()
	var player := _find_player(probe)
	if player != null:
		var spec: Dictionary = _SPECIES[species]
		var clips: Dictionary = spec["clips"]
		for key in _LOOPING:
			if not clips.has(key):
				continue
			var full: String = "%s%s" % [spec["prefix"], clips[key]]
			if player.has_animation(full):
				player.get_animation(full).loop_mode = Animation.LOOP_LINEAR
	probe.free()


## Builds one character. Returns a Node3D shaped exactly like the one
## `Meshes.soldier_body()` hands back as far as its callers are concerned: named
## "SoldierBody", feet on y = 0, facing -Z, carrying a "Weapon" child that
## `Soldier` uses as the muzzle origin. Returns null when the model is absent,
## which is the caller's cue to build boxes instead.
##
## `weapon_mesh` may be null for a species that fights bare-handed.
static func build(species: int, faction: int, variant: int,
		weapon_mesh: Mesh) -> Node3D:
	var scene := _scene(species)
	if scene == null:
		return null
	var spec: Dictionary = _SPECIES[species]

	var root := Node3D.new()
	root.name = "SoldierBody"

	# The rig node holds both corrections: the yaw that turns the model from its
	# native +Z to the project's -Z, and the scale that brings it to 1.80 m.
	var rig := Node3D.new()
	rig.name = "Rig"
	rig.rotation.y = PI
	var k: float = TARGET_HEIGHT / float(spec["height"])
	rig.scale = Vector3(k, k, k)
	root.add_child(rig)

	var model := scene.instantiate() as Node3D
	model.name = "Model"
	rig.add_child(model)

	_tint(model, spec, faction, variant)
	_attach_weapon(root, model, spec, weapon_mesh)
	# No custom_aabb here on purpose. A skinned mesh keeps its bind-space bounds,
	# and the zombie's are four metres too tall, so it is culled later than it
	# needs to be. Tightening them by hand got the box wrong: these meshes are
	# authored Z-up, so the height sits on the mesh's Z and a Y-based box culls
	# the character outright at close range. Over-rendering two dozen soldiers
	# is the cheaper mistake.
	return root


## Repaints the uniform surfaces in the faction colour. The override is set on
## the MeshInstance3D, never on the Mesh: surface materials belong to the
## imported resource and are shared by every soldier on the map, so writing
## there would recolour the whole army at once.
static func _tint(model: Node3D, spec: Dictionary, faction: int,
		variant: int) -> void:
	var names: Array = spec["tint"]
	if names.is_empty():
		return
	var colour := _faction_colour(faction, variant)
	for mi in _meshes(model):
		if mi.mesh == null:
			continue
		for s in mi.mesh.get_surface_count():
			var source := mi.mesh.surface_get_material(s)
			if source == null or not names.has(source.resource_name):
				continue
			mi.set_surface_override_material(s, _tinted(source, colour))


## Faction colour, nudged per variant so a squad is not four clones. Mirrors the
## palette `MatLib` uses for the procedural uniforms.
static func _faction_colour(faction: int, variant: int) -> Color:
	var base: Color
	match faction:
		_F_AXIS:
			base = Palette.FELDGRAU
		_F_NEUTRAL:
			base = Palette.RESISTANCE
		_:
			base = Palette.KHAKI
	# A model lit like a real surface needs more albedo than the flat box
	# uniforms carry, otherwise it reads as a black cut-out.
	base = base * 2.3
	var shade := 1.0 + (float(absi(variant) % 3) - 1.0) * 0.10
	return Color(minf(base.r * shade, 1.0), minf(base.g * shade, 1.0),
			minf(base.b * shade, 1.0))


## A copy of the model's own material in a new colour, so the imported roughness
## and shading survive the recolour. Cached per source material and colour.
static func _tinted(source: Material, colour: Color) -> Material:
	var key: String = "%s:%s" % [source.resource_name, colour.to_html(false)]
	if _tint_cache.has(key):
		return _tint_cache[key] as Material
	var copy := source.duplicate() as Material
	if copy is StandardMaterial3D:
		(copy as StandardMaterial3D).albedo_color = colour
	elif copy is ORMMaterial3D:
		(copy as ORMMaterial3D).albedo_color = colour
	_tint_cache[key] = copy
	return copy


## Hangs the weapon off the hand bone. Two traps here: a child of a Skeleton3D
## inherits the armature's ~100x export scale, and the bone's own axes have
## nothing to do with the world, so the mesh needs both a counter-scale and a
## fixed correction rotation.
static func _attach_weapon(root: Node3D, model: Node3D, spec: Dictionary,
		weapon_mesh: Mesh) -> void:
	var weapon := Node3D.new()
	weapon.name = "Weapon"

	var skeleton := _find_skeleton(model)
	var bone: String = spec["hand_bone"]
	if skeleton == null or skeleton.find_bone(bone) < 0:
		# No usable hand: keep a "Weapon" node anyway, parked where the box
		# soldier used to carry it, because `Soldier` fires from its position.
		weapon.position = Vector3(0.19, 1.19, -0.20)
		root.add_child(weapon)
		_weapon_mesh(weapon, weapon_mesh)
		return

	var attach := BoneAttachment3D.new()
	attach.name = "HandR"
	attach.bone_name = bone
	skeleton.add_child(attach)
	attach.add_child(weapon)

	# Grip alignment, derived instead of guessed. A hand bone points along
	# whatever axis the rigger chose, and the two models disagree; the weapon is
	# modelled barrel down -Z. Cancelling the bone's own rest basis and turning
	# it half a circle leaves the barrel pointing out of the model's face, which
	# after the Rig's yaw is the -Z the project expects.
	var rest := skeleton.get_bone_global_rest(skeleton.find_bone(bone))
	weapon.basis = rest.basis.orthonormalized().inverse() * Basis(Vector3.UP, PI)

	# Undo every scale between `root` and this bone, so the weapon keeps the
	# metric size `Meshes` built it at. The walk already passes through `Rig`,
	# so the rig factor must NOT be applied a second time.
	var inherited := _accumulated_scale(attach, root)
	if inherited > 0.0:
		weapon.scale = Vector3.ONE / inherited
	_weapon_mesh(weapon, weapon_mesh)


static func _weapon_mesh(parent: Node3D, weapon_mesh: Mesh) -> void:
	if weapon_mesh == null:
		return
	var mi := MeshInstance3D.new()
	mi.name = "WeaponMesh"
	mi.mesh = weapon_mesh
	parent.add_child(mi)


## Product of the scales from `node` up to, but not including, `stop`.
static func _accumulated_scale(node: Node3D, stop: Node3D) -> float:
	var out := 1.0
	var cur: Node = node
	while cur != null and cur != stop and cur is Node3D:
		out *= (cur as Node3D).scale.y
		cur = cur.get_parent()
	return out


# --- small tree helpers ------------------------------------------------------

static func _find_player(node: Node) -> AnimationPlayer:
	if node is AnimationPlayer:
		return node as AnimationPlayer
	for child in node.get_children():
		var hit := _find_player(child)
		if hit != null:
			return hit
	return null


static func _find_skeleton(node: Node) -> Skeleton3D:
	if node is Skeleton3D:
		return node as Skeleton3D
	for child in node.get_children():
		var hit := _find_skeleton(child)
		if hit != null:
			return hit
	return null


static func _meshes(node: Node) -> Array[MeshInstance3D]:
	var out: Array[MeshInstance3D] = []
	if node is MeshInstance3D:
		out.append(node as MeshInstance3D)
	for child in node.get_children():
		out.append_array(_meshes(child))
	return out


## Clip table for a species, used by `CharacterAnim`. Empty when unknown.
static func clips(species: int) -> Dictionary:
	if not _SPECIES.has(species):
		return {}
	return _SPECIES[species]["clips"]


static func clip_prefix(species: int) -> String:
	if not _SPECIES.has(species):
		return ""
	return _SPECIES[species]["prefix"]


static func reference_speeds(species: int) -> Vector2:
	if not _SPECIES.has(species):
		return Vector2(1.4, 4.6)
	return Vector2(float(_SPECIES[species]["walk_speed"]),
			float(_SPECIES[species]["run_speed"]))


static func clear_cache() -> void:
	_scene_cache.clear()
	_tint_cache.clear()
