image: google/cloud-sdk:slim

variables:
  GCP_PROJECT_ID: studi-ai
  REGION: europe-west1
  SERVICE_COUNT: studi-ai@studi-ai-454216.iam.gserviceaccount.com
  REPOSITORY: docker-${GCP_PROJECT_ID}-repo 
  IMAGE: europe-west1-docker.pkg.dev/$GCP_PROJECT_ID/$REPOSITORY/$SERVICE_NAME
  ####     VARIABLES SPECIFIQUES :
  SERVICE_NAME: prospect-incoming-callbot

stages:
  - build
  - deploy
  - cleanup

  
before_script:
  - echo $GOOGLE_CREDENTIALS > ${CI_PROJECT_DIR}/google_credentials.json
  - gcloud auth activate-service-account --key-file=${CI_PROJECT_DIR}/google_credentials.json
  - gcloud config set project $GCP_PROJECT_ID
  - gcloud --quiet auth configure-docker europe-west1-docker.pkg.dev

build:
  stage: build
  tags:
    - gcloud,docker
  script:
    - docker build -t $IMAGE .
    - docker push $IMAGE

deploy:
  stage: deploy
  tags:
    - gcloud,docker
  script:
    - echo "Deploying Cloud Run job..."
    - gcloud run jobs deploy $SERVICE_NAME --image $IMAGE --region $REGION --service-account=$SERVICE_COUNT --set-env-vars GOOGLE_CLOUD_PROJECT=$GCP_PROJECT_ID,dest_project_id=$DEST_PROJECT_ID --memory 32Gi --cpu 8

cleanup:
  stage: cleanup
  tags:
    - gcloud,docker
  needs:
    - deploy
  script:
    - docker rmi -f $IMAGE
  when: always