site_name: PIC Prospect Incoming Callbot
site_description: AI-powered phone conversation system that handles incoming calls using Twilio
site_author: Etienne MILLERIOUX
repo_url: https://github.com/your-username/PIC-Prospect_Incoming_Callbot
repo_name: your-username/PIC-Prospect_Incoming_Callbot

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: false
            show_root_heading: true
            show_if_no_docstring: true
            inherited_members: true
            members_order: source
            separate_signature: true
            unwrap_annotated: true
            filters: ["!^_"]
            merge_init_into_class: true
            docstring_section_style: spacy
            signature_crossrefs: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
    - Running the Application: getting-started/running.md
  - Architecture:
    - Overview: architecture/overview.md
    - Agent System: architecture/agents.md
    - Audio Processing: architecture/audio.md
    - External Integrations: architecture/integrations.md
  - API Reference:
    - Endpoints: api/endpoints.md
    - Agents: api/agents.md
    - Managers: api/managers.md
    - Utils: api/utils.md
  - Development:
    - Contributing: development/contributing.md
    - Testing: development/testing.md
    - Deployment: development/deployment.md