"""Scaffolds the workspace where dev agents implement stories.

Python (uv/pytest) is the default; Go (go.mod) and Rust (Cargo) are scaffolded
per ``state.backend_language`` (L2g) so their native test runners work from the
first iteration.
"""

from __future__ import annotations

import re
from pathlib import Path

from ..config import settings
from ..models import ProjectState, UserStory
from ..storage import workspace_dir
from . import toolchain

# The `ui` marker keeps Playwright acceptance tests out of the default suite
# (replayed separately with `uv run pytest -m ui`, where the explicit -m wins).
PYPROJECT_TEMPLATE = """[project]
name = "{package}"
version = "0.1.0"
description = "Generated by Autospec: {name}"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.0",
    "pytest-bdd>=7.0",
    "pytest-json-report>=1.5",{ui_dep}
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["{package}"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-m \\"not ui\\""
markers = ["ui: tests d'acceptance UI Playwright (rejoues via `uv run pytest -m ui`)"]
"""

MAIN_TEMPLATE = '''"""Entry point of the generated application. Dev agents extend this."""


def main() -> None:
    print("Projet généré par Autospec — aucune fonctionnalité câblée pour l'instant.")


if __name__ == "__main__":
    main()
'''

GITIGNORE_TEMPLATE = """.venv/
__pycache__/
*.pyc
.pytest_cache/
autospec-report-*.json
.report.json
"""

# ---- Go (L2g) -------------------------------------------------------------
GO_MOD_TEMPLATE = """module {package}

go 1.21
"""

GO_MAIN_TEMPLATE = """package main

import "fmt"

func main() {{
\tfmt.Println("Projet généré par Autospec — aucune fonctionnalité câblée pour l'instant.")
}}
"""

GO_GITIGNORE = """/bin/
*.exe
"""

# ---- Rust (L2g) -----------------------------------------------------------
CARGO_TOML_TEMPLATE = """[package]
name = "{package}"
version = "0.1.0"
edition = "2021"

[dependencies]
"""

RUST_MAIN_TEMPLATE = """fn main() {{
    println!("Projet généré par Autospec — aucune fonctionnalité câblée pour l'instant.");
}}
"""

RUST_GITIGNORE = """/target/
"""


def package_name(state: ProjectState) -> str:
    slug = re.sub(r"[^a-z0-9_]+", "_", state.name.lower()).strip("_") or "app"
    if slug[0].isdigit():
        slug = f"app_{slug}"
    return slug


def feature_rel_path(story: UserStory) -> str:
    return f"features/{story.id.lower().replace('-', '_')}.feature"


def _ensure(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists():
        path.write_text(content, encoding="utf-8")


def _backend_language(state: ProjectState) -> str:
    lang = getattr(state, "backend_language", "python")
    return toolchain.normalize(getattr(lang, "value", lang))


def scaffold(state: ProjectState) -> Path:
    """Create (idempotently) the workspace skeleton for a project, in the
    project's backend language (L2g)."""
    lang = _backend_language(state)
    if lang == "go":
        return _scaffold_go(state)
    if lang == "rust":
        return _scaffold_rust(state)
    return _scaffold_python(state)


def _scaffold_python(state: ProjectState) -> Path:
    ws = workspace_dir(state.id)
    pkg = package_name(state)
    (ws / pkg).mkdir(parents=True, exist_ok=True)
    (ws / "features").mkdir(exist_ok=True)
    (ws / "tests" / "steps").mkdir(parents=True, exist_ok=True)

    ui_dep = '\n    "pytest-playwright>=0.5",' if settings.ui_tests_enabled else ""
    _ensure(ws / ".gitignore", GITIGNORE_TEMPLATE)
    _ensure(
        ws / "pyproject.toml",
        PYPROJECT_TEMPLATE.format(package=pkg, name=state.name, ui_dep=ui_dep),
    )
    _ensure(ws / pkg / "__init__.py", "")
    _ensure(ws / "tests" / "__init__.py", "")
    _ensure(ws / "tests" / "steps" / "__init__.py", "")
    if settings.ui_tests_enabled:
        (ws / "tests" / "ui").mkdir(parents=True, exist_ok=True)
        _ensure(ws / "tests" / "ui" / "__init__.py", "")
    _ensure(ws / "main.py", MAIN_TEMPLATE)
    return ws


def _scaffold_go(state: ProjectState) -> Path:
    """Go module skeleton: `go test ./...` runs green (no test files) from the
    start, the dev adds `*_test.go` + package code."""
    ws = workspace_dir(state.id)
    pkg = package_name(state)
    (ws / "features").mkdir(parents=True, exist_ok=True)
    _ensure(ws / ".gitignore", GO_GITIGNORE)
    _ensure(ws / "go.mod", GO_MOD_TEMPLATE.format(package=pkg))
    _ensure(ws / "main.go", GO_MAIN_TEMPLATE)
    return ws


def _scaffold_rust(state: ProjectState) -> Path:
    """Cargo binary crate: `cargo test` runs green (0 tests) from the start, the
    dev adds modules + `#[cfg(test)]` tests (or files under `tests/`)."""
    ws = workspace_dir(state.id)
    pkg = package_name(state)
    (ws / "features").mkdir(parents=True, exist_ok=True)
    _ensure(ws / ".gitignore", RUST_GITIGNORE)
    _ensure(ws / "Cargo.toml", CARGO_TOML_TEMPLATE.format(package=pkg))
    _ensure(ws / "src" / "main.rs", RUST_MAIN_TEMPLATE)
    return ws


def write_feature_files(state: ProjectState, stories: list[UserStory]) -> None:
    ws = workspace_dir(state.id)
    for story in stories:
        path = ws / feature_rel_path(story)
        path.parent.mkdir(parents=True, exist_ok=True)
        gherkin = story.gherkin.strip() + "\n"
        path.write_text(gherkin, encoding="utf-8")
