"""Scaffolds the uv-managed Python workspace where dev agents implement stories."""

from __future__ import annotations

import re
from pathlib import Path

from ..models import ProjectState, UserStory
from ..storage import workspace_dir

PYPROJECT_TEMPLATE = """[project]
name = "{package}"
version = "0.1.0"
description = "Generated by Autospec: {name}"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.0",
    "pytest-bdd>=7.0",
    "pytest-json-report>=1.5",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["{package}"]

[tool.pytest.ini_options]
testpaths = ["tests"]
"""

MAIN_TEMPLATE = '''"""Entry point of the generated application. Dev agents extend this."""


def main() -> None:
    print("Projet généré par Autospec — aucune fonctionnalité câblée pour l'instant.")


if __name__ == "__main__":
    main()
'''


def package_name(state: ProjectState) -> str:
    slug = re.sub(r"[^a-z0-9_]+", "_", state.name.lower()).strip("_") or "app"
    if slug[0].isdigit():
        slug = f"app_{slug}"
    return slug


def feature_rel_path(story: UserStory) -> str:
    return f"features/{story.id.lower().replace('-', '_')}.feature"


def scaffold(state: ProjectState) -> Path:
    """Create (idempotently) the workspace skeleton for a project."""
    ws = workspace_dir(state.id)
    pkg = package_name(state)
    (ws / pkg).mkdir(parents=True, exist_ok=True)
    (ws / "features").mkdir(exist_ok=True)
    (ws / "tests" / "steps").mkdir(parents=True, exist_ok=True)

    def _ensure(path: Path, content: str) -> None:
        if not path.exists():
            path.write_text(content, encoding="utf-8")

    _ensure(ws / "pyproject.toml", PYPROJECT_TEMPLATE.format(package=pkg, name=state.name))
    _ensure(ws / pkg / "__init__.py", "")
    _ensure(ws / "tests" / "__init__.py", "")
    _ensure(ws / "tests" / "steps" / "__init__.py", "")
    _ensure(ws / "main.py", MAIN_TEMPLATE)
    return ws


def write_feature_files(state: ProjectState, stories: list[UserStory]) -> None:
    ws = workspace_dir(state.id)
    for story in stories:
        path = ws / feature_rel_path(story)
        path.parent.mkdir(parents=True, exist_ok=True)
        gherkin = story.gherkin.strip() + "\n"
        path.write_text(gherkin, encoding="utf-8")
