form:
  name: "example_form"
  groups:
    - name: "personal_info"
      description: "Personal Information"
      fields:
        - name: "civility"
          description: "User civility"
          type: "string"
          min_size_or_value: 1
          max_size_or_value: 10
          optional: false
        - name: "last_name"
          description: "User last name"
          type: "string"
          min_size_or_value: 2
          max_size_or_value: 50
          optional: false
        - name: "first_name"
          description: "User first name"
          type: "string"
          min_size_or_value: 2
          max_size_or_value: 50
          optional: false
    - name: "contact"
      description: "Contact Information"
      fields:
        - name: "email"
          description: "User email address"
          type: "string"
          min_size_or_value: 5
          max_size_or_value: 100
          regex: "^[\\w\\.-]+@[\\w\\.-]+\\.[a-zA-Z]{2,}$"
          optional: false
        - name: "phone_number"
          description: "User phone number"
          type: "string"
          min_size_or_value: 5
          max_size_or_value: 30
          regex: "^\\d{10}$"
          optional: false
    - name: "postal_address"
      description: "Postal Address"
      fields:
        - name: "address_1"
          description: "Address line 1"
          type: "string"
          min_size_or_value: 2
          max_size_or_value: 100
          optional: false
        - name: "address_2"
          description: "Address line 2"
          type: "string"
          min_size_or_value: 0
          max_size_or_value: 100
          optional: true
        - name: "postal_code"
          description: "Postal code"
          type: "string"
          regex: "^\\d{5}$"
          optional: false
        - name: "city"
          description: "City"
          type: "string"
          min_size_or_value: 3
          max_size_or_value: 50
          optional: false
        - name: "country"
          description: "Country"
          type: "string"
          min_size_or_value: 2
          max_size_or_value: 50
          optional: false
    - name: "training_preference"
      description: "Training Preference"
      fields:
        - name: "field_of_study"
          description: "Field of study"
          type: "string"
          min_size_or_value: 2
          max_size_or_value: 100
          optional: false
        - name: "training_name"
          description: "Selected training name"
          type: "string"
          min_size_or_value: 10
          max_size_or_value: 100
          optional: false