form:
  name: "example_form"
  description: "Formulaire d'exemple"
  groups:
    - name: "personal_info"
      description: "Personal Information"
      fields:
        - name: "civility"
          description: "User civility"
          type: "string"
          min_size_or_value: 1
          max_size_or_value: 10
          optional: false
          allowed_values: [["M.", "Monsieur", "Mr", "homme"], ["Mme", "Madame", "Mrs", "femme"], ["Dr", "docteur"], "autre"]
        - name: "last_name"
          description: "User last name"
          type: "string"
          min_size_or_value: 2
          max_size_or_value: 50
          optional: false
        - name: "first_name"
          description: "User first name"
          type: "string"
          min_size_or_value: 2
          max_size_or_value: 50
          optional: false
    - name: "postal_address"
      description: "Postal Address"
      fields:
        - name: "address_1"
          description: "Address number and street name"
          type: "string"
          min_size_or_value: 2
          max_size_or_value: 100
          optional: false
        - name: "address_2"
          description: "Address complement"
          type: "string"
          min_size_or_value: 0
          max_size_or_value: 100
          optional: true
        - name: "postal_code"
          description: "Postal code"
          type: "string"
          regex: "^\\d{5}$"
          regex_description: "The postal code should be exactly 5 digits long"
          optional: false
        - name: "city"
          description: "City"
          type: "string"
          min_size_or_value: 3
          max_size_or_value: 50
          optional: false
        - name: "country"
          description: "Country"
          type: "string"
          min_size_or_value: 2
          max_size_or_value: 50
          optional: true
          default_value: "France"
    - name: "contact"
      description: "Contact Information"
      fields:
        - name: "email"
          description: "User email address"
          type: "string"
          min_size_or_value: 5
          max_size_or_value: 100
          regex: "^[\\w\\.-]+@[\\w\\.-]+\\.[a-zA-Z]{2,}$"
          regex_description: "The email address should respect the following format: 'xxx@yyy.zz'"
          optional: false
        - name: "phone_number"
          description: "User phone number"
          type: "string"
          min_size_or_value: 5
          max_size_or_value: 30
          regex: "^(?:(?:\\+\\d{2}(?: ?\\d){9})|(?:(?:\\d ?){9}\\d))$"
          regex_description: "The phone number should be either: 10 digits long, or a plus followed by the country code of 2 digits followed by 9 digits. Spaces are allowed between digits."
          optional: false
    - name: "training_preference"
      description: "Training Preference"
      fields:
        - name: "field_of_study"
          description: "Field of study"
          type: "string"
          min_size_or_value: 2
          max_size_or_value: 100
          optional: false
          allowed_values: ["IT", "RH", "Comptabilité", "Marketing", "Vente", "Communication", "Management", "Finance", "Logistique", "Autre"]
        - name: "training_name"
          description: "Selected training name"
          type: "string"
          min_size_or_value: 10
          max_size_or_value: 100
          optional: false