// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AcceptanceTests
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class RechercheDApprenantsParParcoursFeature : object, Xunit.IClassFixture<RechercheDApprenantsParParcoursFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "use_case3.feature"
#line hidden
        
        public RechercheDApprenantsParParcoursFeature(RechercheDApprenantsParParcoursFeature.FixtureData fixtureData, AcceptanceTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("fr-FR"), "", "Recherche d’apprenants par parcours", null, ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Recherche par sélection de parcours d’intérêt")]
        [Xunit.TraitAttribute("FeatureTitle", "Recherche d’apprenants par parcours")]
        [Xunit.TraitAttribute("Description", "Recherche par sélection de parcours d’intérêt")]
        public void RechercheParSelectionDeParcoursDInteret()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Recherche par sélection de parcours d’intérêt", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 3
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
  testRunner.Given("je suis inscrit en tant qu’apprenant sur le LMS", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Etant donné que ");
#line hidden
#line 5
  testRunner.And("j’ai accédé au module d’annuaire des apprenants", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Et que ");
#line hidden
#line 6
  testRunner.When("je sélectionne un ou plusieurs parcours d’intérêt", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Lorsque ");
#line hidden
#line 7
  testRunner.Then("je devrais voir la liste des apprenants qui ont choisi ce(s) parcours", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Alors ");
#line hidden
#line 8
  testRunner.And("les résultats devraient être limités aux apprenants ayant partagé cette informati" +
                        "on", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Et ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Recherche par recommandations automatiques basées sur les inscriptions")]
        [Xunit.TraitAttribute("FeatureTitle", "Recherche d’apprenants par parcours")]
        [Xunit.TraitAttribute("Description", "Recherche par recommandations automatiques basées sur les inscriptions")]
        public void RechercheParRecommandationsAutomatiquesBaseesSurLesInscriptions()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Recherche par recommandations automatiques basées sur les inscriptions", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 10
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 11
  testRunner.Given("je suis inscrit en tant qu’apprenant sur le LMS", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Etant donné que ");
#line hidden
#line 12
  testRunner.And("j’ai accédé au module d’annuaire des apprenants", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Et que ");
#line hidden
#line 13
  testRunner.When("je n’ai sélectionné aucun parcours d’intérêt", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Lorsque ");
#line hidden
#line 14
  testRunner.Then("je devrais voir une liste d’apprenants recommandés", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Alors ");
#line hidden
#line 15
  testRunner.And("les résultats devraient être limités aux apprenants ayant partagé cette informati" +
                        "on", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Et ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                RechercheDApprenantsParParcoursFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                RechercheDApprenantsParParcoursFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
